version: '3'

services:
  #  minio:
  #    image: "minio/minio"
  #    restart: always
  #    environment:
  #      MINIO_ACCESS_KEY: OR7DZ0AQRAEP1EGIXBXG
  #      MINIO_SECRET_KEY: dJSQvadUHWz6rxuRwipsQHBm3Z1XacIkdKqYFyUP
  #    command: "server /data"
  #    ports:
  #      - 9000:9000
  postgres:
    image: "postgres"
    restart: always
    ports:
      - 6667:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "default"
#    network_mode: host
#  jaeger:
#    image: "jaegertracing/all-in-one:1.14"
#    restart: always
#    ports:
#      - 5775:5775/udp
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
#      - 16686:16686
#      - 14268:14268
#      - 9411:9411
#    network_mode: host