port: ":3000"
env: "dev"
host: "http://localhost:3000"
admin:
  login: admin
  password: password
oauth:
  sessionCookie:
    name: "eblog_session"
    domain: "localhost"
    path: "/"
    max_age: 300
    same_site: 1
    secure: false
  google:
    userRedirects:
      onSuccess: "http://localhost:8080/home"
      onFailure: "http://localhost:8080"
    redirectURL: "http://localhost:3000/api/v1/google/oauth/callback"
    clientID: "203743370138-7o73o9s8feet82bbkgqqrn8lpgue8k2i.apps.googleusercontent.com"
    clientSecret: "UdtS64NVSlwPcrzyQZqWP-bm"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.email"
      - "https://www.googleapis.com/auth/userinfo.profile"
    userInfoURL: "https://www.googleapis.com/oauth2/v2/userinfo"
  github:
    userRedirects:
      onSuccess: "http://localhost:8081/home"
      onFailure: "http://localhost:8081"
    redirectURL: "http://localhost:3000/api/v1/github/oauth/callback"
    clientID: "9606b1258a79ed9b5d32"
    clientSecret: "aa0cc36e475efca3a2393963ad370f3d638d061d"
    scopes:
      - "login:birthday"
      - "login:email"
      - "login:info"
      - "login:avatar"
    userInfoURL: "https://api.github.com/user"
tracer:
  jaeger:
    collectorEndpoint: "http://localhost:14268/api/traces"
    serviceName: "bbackend"
databases:
  postgres: "postgres://postgres:postgres@localhost:6667/bback?sslmode=disable"
objectStorage:
  minio:
    host: localhost:9009
    accessKeyID: OR7DZ0AQRAEP1EGIXBXG
    secretAccessKey: dJSQvadUHWz6rxuRwipsQHBm3Z1XacIkdKqYFyUP
    useSSL: false

